import type { Announcement, BlogPost, EventItem, GalleryItem, TeamMember } from '@/types';

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    slug: 'dawit-mengistu',
    name: 'Dawit Mengistu',
    amharicName: 'ዳዊት መንግስቱ',
    role: 'Artistic Director',
    amharicRole: 'ጥበባዊ ዳይሬክተር',
    discipline: 'Circus',
    amharicDiscipline: 'ሰርከስ',
    bio: 'Dawit directs the company\'s physical theatre language, building aerial sequences that sit inside Ethiopian storytelling rather than on top of it. He trained in Addis Ababa and later studied ensemble circus direction in Europe before returning to form the Kin rehearsal method.',
    amharicBio: 'ዳዊት የቡድኑን የአክሮባቲክስ እና የቲያትር እንቅስቃሴዎችን ይመራል። ከአውሮፓና አዲስ አበባ ባገኘው የብዙ ዓመታት ልምድ የኢትዮጵያን ባህላዊ ታሪኮች በመድረክ ላይ በከፍተኛ ጥራት ያቀርባል።',
    photoUrl: '/images/team/dawit.jpg',
    skills: ['Aerial direction', 'Ensemble composition', 'Rehearsal pedagogy'],
    amharicSkills: ['የአየር ላይ ትይንት አመራር', 'የቡድን ቅንብር', 'የልምምድ ዘዴዎች'],
    socialLinks: { instagram: '#' },
    featured: true,
  },
  {
    id: '2',
    slug: 'selamawit-worku',
    name: 'Selamawit Worku',
    amharicName: 'ሰላማዊት ወርቁ',
    role: 'Principal Krar & Voice',
    amharicRole: 'ዋና ክራር መቺና ድምፃዊ',
    discipline: 'Music',
    amharicDiscipline: 'ሙዚቃ',
    bio: 'Selamawit grew up around Azmari houses in Gondar and now writes arrangements that keep Tizita phrasing intact while making space for contemporary staging. She leads the company\'s evening music residencies.',
    amharicBio: 'ሰላማዊት በጎንደር የአዝማሪ ባህል ውስጥ ያደገች ሲሆን፣ የትዝታ ቅኝትንና ጥንታዊ የክራር ድምፆችን በዘመናዊ ጥበብ አዋህዳ ታቀርባለች።',
    photoUrl: '/images/team/selamawit.jpg',
    skills: ['Krar', 'Vocal arrangement', 'Tizita repertoire'],
    amharicSkills: ['ክራር', 'የድምፅ ቅንብር', 'የትዝታ ቅኝት'],
    socialLinks: { instagram: '#' },
    featured: true,
  },
  {
    id: '3',
    slug: 'yared-kebede',
    name: 'Yared Kebede',
    amharicName: 'ያሬድ ከበደ',
    role: 'Master Drummer',
    amharicRole: 'የከበሮ መምህር',
    discipline: 'Music',
    amharicDiscipline: 'ሙዚቃ',
    bio: 'Yared maps ceremonial kebero patterns from Tigray, Wollo, and Sidama into scores that circus artists can physically count. He also mentors weekend youth percussion circles in Entoto.',
    amharicBio: 'ያሬድ ከትግራይ፣ ወሎና ሲዳማ ያሉ ባህላዊ የከበሮ ምቶችን በአክሮባቲክስ እንቅስቃሴዎች ውስጥ የሚያቀናጅ ባለሙያ ነው። በእንቶቶ የወጣቶች ከበሮ ልምምድ ያስተምራል።',
    photoUrl: '/images/team/yared.jpg',
    skills: ['Kebero', 'Polyrhythm', 'Youth teaching'],
    amharicSkills: ['ከበሮ', 'ፖሊሪዝም', 'የወጣቶች ስልጠና'],
    featured: true,
  },
  {
    id: '4',
    slug: 'hiwot-tadesse',
    name: 'Hiwot Tadesse',
    amharicName: 'ህይወት ታደሰ',
    role: 'Lead Choreographer',
    amharicRole: 'ዋና ኮሪዮግራፈር',
    discipline: 'Dance',
    amharicDiscipline: 'ውዝዋዜ',
    bio: 'Hiwot studies Eskista as a technical system: shoulder micro-timing, breath, and weight. She translates that vocabulary onto floorwork and onto aerial apparatus without flattening the original form.',
    amharicBio: 'ህይወት የእስክስታንና የኢትዮጵያ የተለያዩ ብሔረሰቦች ውዝዋዜዎችን በዘመናዊ መድረክ ላይ በከፍተኛ ጥራት የምታቀናጅ ባለሙያ ናት።',
    photoUrl: '/images/team/hiwot.jpg',
    skills: ['Eskista', 'Contemporary floorwork', 'Stage composition'],
    amharicSkills: ['እስክስታ', 'ዘመናዊ የሜዳ ውዝዋዜ', 'የመድረክ ቅንብር'],
    featured: true,
  },
  {
    id: '5',
    slug: 'mekdes-alemu',
    name: 'Mekdes Alemu',
    amharicName: 'መቅደስ አለሙ',
    role: 'Community Programmes Lead',
    amharicRole: 'የማህበረሰብ ፕሮግራሞች መሪ',
    discipline: 'Community',
    amharicDiscipline: 'ማኅበረሰብ',
    bio: 'Mekdes designs Kin\'s open workshops, school visits, and fellowship logistics. She coordinates cultural education programmes so young artists build real careers.',
    amharicBio: 'መቅደስ የኪን የማህበረሰብ አውደ ጥናቶችንና የወጣቶች ትምህርቶችን ታስተላልፋለች። ወጣት አርቲስቶች በባህላዊ ጥበባት እንዲያድጉ ታመቻቻለች።',
    photoUrl: '/images/team/mekdes.jpg',
    skills: ['Programme design', 'Partnerships', 'Access'],
    amharicSkills: ['የፕሮግራም ዝግጅት', 'ትብብር', 'ዕድሎች'],
    featured: true,
  },
  {
    id: '6',
    slug: 'nahom-girma',
    name: 'Nahom Girma',
    amharicName: 'ናሆም ግርማ',
    role: 'Aerialist & Rigger',
    amharicRole: 'የአየር ላይ አክሮባት እና ሪገር',
    discipline: 'Circus',
    amharicDiscipline: 'ሰርከስ',
    bio: 'Nahom is the company\'s lead rigger and a specialist in straps. His work is quiet and precise: load calculations and high aerial safety.',
    amharicBio: 'ናሆም በአየር ላይ ገመድና መሣሪያዎች አክሮባቲክስ የሰለጠነ ባለሙያ ሲሆን፣ የመድረክ ደህንነትንና ጥራትን ያረጋግጣል።',
    photoUrl: '/images/team/nahom.jpg',
    skills: ['Straps', 'Rigging', 'Safety direction'],
    amharicSkills: ['የአየር ገመድ', 'የመሣሪያ ዝግጅት', 'የደህንነት ቁጥጥር'],
    featured: false,
  },
  {
    id: '7',
    slug: 'rahel-tesfaye',
    name: 'Rahel Tesfaye',
    amharicName: 'ራሄል ተስፋዬ',
    role: 'Washint & Wind Arranger',
    amharicRole: 'ዋሽንት መቺና የዜማ አቀናባሪ',
    discipline: 'Music',
    amharicDiscipline: 'ሙዚቃ',
    bio: 'Rahel writes wind lines that sit between ceremony and theatre. She treats the washint as a lead voice in all sanctuary coffee evenings.',
    amharicBio: 'ራሄል በዋሽንት ድምፅ የኢትዮጵያን ባህላዊ መንፈስና ዜማ በመድረክ ላይ የምታቀርብ ጥበባዊት ናት።',
    photoUrl: '/images/team/rahel.jpg',
    skills: ['Washint', 'Ensemble writing', 'Improvisation'],
    amharicSkills: ['ዋሽንት', 'የቡድን ዜማ', 'ቅኝት'],
    featured: false,
  },
  {
    id: '8',
    slug: 'abesolom-desta',
    name: 'Abesolom Desta',
    amharicName: 'አበሶሎም ደስታ',
    role: 'Traditional Arts Coordinator',
    amharicRole: 'የባህላዊ ጥበባት አስተባባሪ',
    discipline: 'Traditional Arts',
    amharicDiscipline: 'ባህላዊ ጥበባት',
    bio: 'Abesolom works with weavers, coffee ceremony hosts, and instrument makers so that Kin stages preserve living craft.',
    amharicBio: 'አበሶሎም ከባህላዊ አልባሳት፣ ቡና ሥርዓትና የሙዚቃ መሣሪያ ሠሪዎች ጋር በመሆን ጥንታዊ ቅርሶችን ያስተዋውቃል።',
    photoUrl: '/images/team/abesolom.jpg',
    skills: ['Craft liaison', 'Documentation', 'Ceremony staging'],
    amharicSkills: ['የባህል ጥበብ', 'ሰነድ ማዘጋጀት', 'የሥርዓት ዝግጅት'],
    featured: false,
  },
];

export const mockEvents: EventItem[] = [
  {
    id: 'e1',
    slug: 'echoes-of-the-ridge',
    title: 'Echoes of the Ridge',
    amharicTitle: 'የደጋው ንቅናቄ',
    date: '2026-10-18T18:30:00+03:00',
    time: '18:30–21:30 EAT',
    location: 'Addis Ababa',
    amharicLocation: 'አዲስ አበባ',
    venue: 'National Theatre Main Hall',
    amharicVenue: 'ብሔራዊ ቲያትር ዋና አዳራሽ',
    category: 'Circus',
    amharicCategory: 'ሰርከስ',
    description:
      'An evening-length work about highland trade routes told through human pyramids, masinko underscoring, and aerial phrases that follow the contour of a ridge line. The company performs with a live percussion quartet.',
    amharicDescription:
      'የደጋው ንቅናቄ በሰው ፒራሚድ፣ በማሲንቆና በከበሮ ምት የታገዘ የሁለት ሰዓት ትይንት ነው። የባህል አክሮባቶችና ሙዚቀኞች በአንድነት ያቀርቡታል።',
    imageUrl: '/images/hero/kin-ethiopia-golden-banner.jpg',
    performers: ['Kin Performance Ensemble', 'Selamawit Worku', 'Addis Kebero Quartet'],
    amharicPerformers: ['የኪን ትይንት ቡድን', 'ሰላማዊት ወርቁ', 'የአዲስ ከበሮ ቡድን'],
    status: 'upcoming',
    ticketUrl: '#',
  },
  {
    id: 'e2',
    slug: 'buna-rhythms-night',
    title: 'Buna Rhythms',
    amharicTitle: 'የቡና ዜማ',
    date: '2026-11-05T17:00:00+03:00',
    time: '17:00–20:30 EAT',
    location: 'Addis Ababa',
    amharicLocation: 'አዲስ አበባ',
    venue: 'Kin Pavilion, Entoto',
    amharicVenue: 'የኪን ፓቪሊዮን እንቶቶ',
    category: 'Traditional Arts',
    amharicCategory: 'ባህላዊ ጥበባት',
    description:
      'A seated coffee sanctuary with live washint and krar, frankincense, and short stories between roasts. Capacity is limited so the room can stay conversational rather than theatrical.',
    amharicDescription:
      'በቡና ሥርዓት፣ በዋሽንትና ክራር ዜማ የታጀበ ባህላዊ ምሽት። ከእጣን ማዕዛ ጋር የኢትዮጵያ ወግና ታሪክ ይቀርባል።',
    imageUrl: '/images/culture/kin-vocalists-performance.jpg',
    performers: ['Rahel Tesfaye', 'Yared Kebede', 'Kin hosts'],
    amharicPerformers: ['ራሄል ተስፋዬ', 'ያሬድ ከበደ', 'የኪን አስተናጋጆች'],
    status: 'upcoming',
    ticketUrl: '#',
  },
  {
    id: 'e3',
    slug: 'youth-open-rehearsal',
    title: 'Youth Open Rehearsal',
    amharicTitle: 'የወጣቶች ክፍት ልምምድ',
    date: '2026-09-26T10:00:00+03:00',
    time: '10:00–13:00 EAT',
    location: 'Addis Ababa',
    amharicLocation: 'አዲስ አበባ',
    venue: 'Kin Training Studio',
    amharicVenue: 'የኪን ስልጠና ስቱዲዮ',
    category: 'Community',
    amharicCategory: 'ማኅበረሰብ',
    description:
      'Families are invited to watch a working rehearsal and then join a short floor-tumbling and kebero session. No prior training is required.',
    amharicDescription:
      'ቤተሰቦች በልምምዱ ላይ በመገኘት የአክሮባቲክስና የከበሮ ስልጠናዎችን በነጻ እንዲለማመዱ ተጋብዘዋል።',
    imageUrl: '/images/events/kin-cultural-exchange.jpg',
    performers: ['Mekdes Alemu', 'Nahom Girma'],
    amharicPerformers: ['መቅደስ አለሙ', 'ናሆም ግርማ'],
    status: 'upcoming',
  },
  {
    id: 'e4',
    slug: 'fire-and-clay',
    title: 'Fire & Clay',
    amharicTitle: 'እሳት እና ሸክላ',
    date: '2025-12-12T19:00:00+03:00',
    time: '19:00 EAT',
    location: 'Hawassa',
    amharicLocation: 'ሀዋሳ',
    venue: 'Lakefront Cultural Hall',
    amharicVenue: 'የሐይቅ ዳር ባህል አዳራሽ',
    category: 'Cultural Events',
    amharicCategory: 'ባህላዊ ዝግጅቶች',
    description:
      'A 2025 company gathering on the lakeshore with hoop aerials, southern percussion, and a closing coffee circle.',
    amharicDescription:
      'በሐዋሳ ሐይቅ ዳር የተደረገ የሰርከስና የደቡብ ብሔረሰቦች ከበሮ ምት ታላቅ የባህል ዝግጅት።',
    imageUrl: '/images/hero/kin-grand-stage-ensemble.jpg',
    performers: ['Full Kin Company'],
    amharicPerformers: ['ሙሉ የኪን ቡድን'],
    status: 'past',
  },
  {
    id: 'e5',
    slug: 'gondar-night-songs',
    title: 'Night Songs in Gondar',
    amharicTitle: 'የጎንደር ሌሊት ዜማዎች',
    date: '2025-08-22T19:30:00+03:00',
    time: '19:30 EAT',
    location: 'Gondar',
    amharicLocation: 'ጎንደር',
    venue: 'Fasil Cultural Centre',
    amharicVenue: 'ፋሲል ባህል ማዕከል',
    category: 'Music',
    amharicCategory: 'ሙዚቃ',
    description:
      'An outdoor programme of Azmari-informed song with restrained circus interludes recorded for the company archive.',
    amharicDescription:
      'በታሪካዊቷ ጎንደር ከተማ የተካሄደ የአዝማሪ ሙዚቃና የባህል ሰርከስ ምሽት።',
    imageUrl: '/images/culture/kin-vocalists-performance.jpg',
    performers: ['Selamawit Worku', 'Rahel Tesfaye'],
    amharicPerformers: ['ሰላማዊት ወርቁ', 'ራሄል ተስፋዬ'],
    status: 'past',
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 'b1',
    slug: 'geometry-of-the-kebero',
    title: 'The Geometry of the Kebero',
    amharicTitle: 'የከበሮ ምትና ጂኦሜትሪ',
    excerpt:
      'How a dual-headed drum teaches balance to acrobats, and why tempo is the wrong word for ceremonial time.',
    amharicExcerpt:
      'ባለሁለት ወገን ከበሮ ለአክሮባቶች ሚዛን መጠበቅን እንዴት እንደሚያስተምርና የከበሮ ምት ምስጢር።',
    content: `The kebero is two rooms sharing one body. The larger head holds a long, warm tone. The smaller head answers with a dry slap. Players move between those rooms the way a good ensemble moves between earth and air.

In Kin rehearsals we do not treat percussion as a metronome glued under circus. The body has to understand rebound. When Yared plays a Wollo pattern, the aerialists count the hide, not a click track. A delayed second strike changes how a pyramid unloads. A rushed slap makes a strap phrase look anxious.

This is why we invite musicians into the studio from week one. Costume, lighting, and flying can wait. The first agreement is time: who holds it, who answers it, and when the room is allowed to breathe.`,
    amharicContent: `ከበሮ በአንድ አካል ውስጥ ሁለት ድምፆችን የያዘ የኢትዮጵያ ጥንታዊ የሙዚቃ መሣሪያ ነው። ትልቁ ወገን ጥልቅና ሞቅ ያለ ድምፅ ሲሰጥ፣ ትንሹ ወገን ደግሞ ፈጣንና የጠራ ምት ይሰጣል።

በኪን ልምምድ ውስጥ ከበሮን እንደ አጋዥ ብቻ አንጠቀምበትም። የአክሮባቲክስ አርቲስቶቻችን አካል ከከበሮው ምት ጋር ይንቀሳቀሳል። ያሬድ የወሎን ቅኝት ሲጫወት፣ የአየር ላይ አክሮባቶች ድምፁን በመከተል ይበርራሉ።

ለዚህ ነው ከልምምድ መጀመሪያ ጀምሮ ሙዚቀኞችን የምንጋብዘው። አልባሳትና መብራቶች ሊቆዩ ይችላሉ፤ ዋናው ስምምነት ጊዜና ምት ነው፡ ማን ይይዘዋል፣ ማን ይመልሰዋል፣ እና መቼ መድረኩ ይተነፍሳል።`,
    featuredImage: '/images/hero/kin-ethiopia-golden-banner.jpg',
    author: { name: 'Yared Kebede', amharicName: 'ያሬድ ከበደ', role: 'Master Drummer', amharicRole: 'የከበሮ መምህር' },
    category: 'Music',
    amharicCategory: 'ሙዚቃ',
    tags: ['Percussion', 'Rehearsal', 'Kebero'],
    publishedAt: '2026-08-20',
    updatedAt: '2026-08-22',
    readingTime: '5 min read',
    amharicReadingTime: 'የ5 ደቂቃ ንባብ',
    featured: true,
  },
  {
    id: 'b2',
    slug: 'eskista-in-the-air',
    title: 'Eskista in the Air',
    amharicTitle: 'እስክስታ በአየር ላይ',
    excerpt:
      'Shoulder isolations were never meant for silk. Translating them upward without turning them into decoration.',
    amharicExcerpt:
      'የእስክስታ እንቅስቃሴዎችን በአየር ገመድ ላይ በመቀናጀት አዲስ ጥበባዊ ውበት መፍጠር።',
    content: `Eskista lives in the torso. The floor gives the dancer a place to send force. Silk gives almost none. If you copy the steps twelve metres up, you get a souvenir of dance, not dance.

Hiwot's current research is smaller: which micro-isolations survive when the pelvis cannot plant. The answer so far is breath, neck, and the timing of a delayed shoulder. Nahom then builds a strap phrase that can host those timings rather than fight them.`,
    amharicContent: `እስክስታ በትከሻና በደረት እንቅስቃሴ ላይ የተመሰረተ ነው። ምድር ለተዋዛዋጁ ኃይል ይሰጠዋል፤ አየር ላይ ገመድ ግን የተለየ ነው።

ህይወት የምታደርገው ጥናት፡ በአየር ላይ ገመድ ላይ ሆኖ እስክስታን እንዴት በከፍተኛ ጥራት ማቅረብ እንደሚቻል ነው። ከናሆም ጋር በመሆን የገመድ አክሮባቲክስን ከእስክስታ ጋር አቀናጅተዋል።`,
    featuredImage: '/images/hero/kin-grand-stage-ensemble.jpg',
    author: { name: 'Hiwot Tadesse', amharicName: 'ህይወት ታደሰ', role: 'Lead Choreographer', amharicRole: 'ዋና ኮሪዮግራፈር' },
    category: 'Circus',
    amharicCategory: 'ሰርከስ',
    tags: ['Dance', 'Aerial', 'Research'],
    publishedAt: '2026-07-14',
    readingTime: '6 min read',
    amharicReadingTime: 'የ6 ደቂቃ ንባብ',
  },
  {
    id: 'b3',
    slug: 'coffee-as-rehearsal',
    title: 'Coffee Is a Rehearsal',
    amharicTitle: 'ቡና እንደ ልምምድ',
    excerpt:
      'Why the company treats the jebena as a staging problem, not a hospitality extra.',
    amharicExcerpt:
      'ጀበናና የቡና ሥርዓት በመድረካችን ላይ እንዴት ታላቅ የባህል ትይንት እንደሚሆን።',
    content: `A coffee ceremony already has dramaturgy: fire, waiting, three rounds, talk. If a theatre company adds it as interval flavour, the form collapses into scent.

Abesolom and the hosts now rehearse Buna Rhythms the way we rehearse aerials. Who carries the tray. When frankincense enters. How long the room stays quiet after the first pour.`,
    amharicContent: `የቡና ሥርዓት በራሱ ቲያትራዊ ውበት አለው፡ እሳት፣ መጠበቅ፣ ሦስት ዙርና ውይይት።

አበሶሎም እና ቡድኑ የቡና ሥርዓትን እንደ አክሮባቲክስ ልምምድ በጥንቃቄ ያዘጋጁታል። ማነው ፌንጣውን የሚያቀርበው፣ እጣን መቼ ይጨሳል፣ ራሄል በዋሽንት መቼ ታጅባለች የሚለው ሁሉ በልምምድ ይወሰናል።`,
    featuredImage: '/images/culture/kin-vocalists-performance.jpg',
    author: { name: 'Abesolom Desta', amharicName: 'አበሶሎም ደስታ', role: 'Traditional Arts Coordinator', amharicRole: 'የባህላዊ ጥበባት አስተባባሪ' },
    category: 'Ethiopian Heritage',
    amharicCategory: 'የኢትዮጵያ ቅርስ',
    tags: ['Coffee', 'Ceremony', 'Staging'],
    publishedAt: '2026-06-02',
    readingTime: '4 min read',
    amharicReadingTime: 'የ4 ደቂቃ ንባብ',
  },
  {
    id: 'b4',
    slug: 'open-studio-notes',
    title: 'Notes from the Open Studio',
    amharicTitle: 'ከክፍት ስቱዲዮ የተገኙ ማስታወሻዎች',
    excerpt:
      'What we learned when parents, neighbours, and first-year students sat in on a working day.',
    amharicExcerpt:
      'ጎረቤቶችና ወላጆች በስቱዲዮ ልምምዳችን ላይ ሲገኙ ያገኘነው ልምድና ደስታ።',
    content: `The first public rehearsal was messy in useful ways. Children asked about ropes. A kebero student corrected our count. A parent asked why we do not sell tickets at the door for everything.

Mekdes now keeps a simple rule: one Saturday a month the studio is watchable. Not a show. A working room with chairs along the wall and tea at the back.`,
    amharicContent: `የመጀመሪያው ክፍት ልምምድ አነቃቂ ነበር። ህፃናት ስለ ገመድ ጠየቁ፣ የወጣቶች ከበሮ ተማሪዎች ምታችንን አስተካከሉ!

መቅደስ በወር አንድ ቅዳሜ ስቱዲዮውን ለህዝብ ክፍት ታደርጋለች። ተመልካቾች ተቀምጠው ልምምዱን ያያሉ፣ የባህል ሻይም ይጠጣሉ።`,
    featuredImage: '/images/events/kin-cultural-exchange.jpg',
    author: { name: 'Mekdes Alemu', amharicName: 'መቅደስ አለሙ', role: 'Community Programmes Lead', amharicRole: 'የማህበረሰብ ፕሮግራሞች መሪ' },
    category: 'Community',
    amharicCategory: 'ማኅበረሰብ',
    tags: ['Access', 'Youth', 'Studio'],
    publishedAt: '2026-05-11',
    readingTime: '4 min read',
    amharicReadingTime: 'የ4 ደቂቃ ንባብ',
  },
  {
    id: 'b5',
    slug: 'why-we-tour-slowly',
    title: 'Why We Tour Slowly',
    amharicTitle: 'ለምን በዝግታ እንጓዛለን?',
    excerpt:
      'International invitations are welcome. Extracting a company from its rehearsal city is not a flex.',
    amharicExcerpt:
      'ዓለም አቀፍ ግብዣዎችን እንቀበላለን፤ ነገር ግን የሀገራችንን ስቱዲዮ ሳንተው በዝግታ እንጓዛለን።',
    content: `Kin will travel. We already have conversations with festivals that understand circus and music as equal partners. We will not, however, empty the Entoto studio for months at a time.

The fellowship, the weekend workshops, and the instrument makers all depend on a room that stays open.`,
    amharicContent: `ኪን ወደ ዓለም ይጓዛል። ከዓለም አቀፍ ፌስቲቫሎች ጋር እንሰራለን፤ ነገር ግን የእንቶቶ ስቱዲዮችንን አንዘጋም። የወጣቶች ስልጠናና የባህል ስራዎቻችን ሁሌም ክፍት ናቸው።`,
    featuredImage: '/images/events/kin-cultural-exchange.jpg',
    author: { name: 'Dawit Mengistu', amharicName: 'ዳዊት መንግስቱ', role: 'Artistic Director', amharicRole: 'ጥበባዊ ዳይሬክተር' },
    category: 'Behind the Scenes',
    amharicCategory: 'ከመጋረጃው በስተጀርባ',
    tags: ['Touring', 'Producing', 'Care'],
    publishedAt: '2026-04-18',
    readingTime: '5 min read',
    amharicReadingTime: 'የ5 ደቂቃ ንባብ',
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 'a1',
    slug: 'young-artist-fellowship',
    title: '2026/27 Young Artist Fellowship is open',
    amharicTitle: 'የ2026/27 የወጣት አርቲስቶች ድጋፍ ተከፍቷል',
    date: '2026-09-01',
    category: 'Auditions',
    amharicCategory: 'መልመጃዎች',
    summary:
      'A twelve-month residency for acrobats, traditional instrumentalists, and physical actors based in Ethiopia.',
    amharicSummary:
      'ለአክሮባቶች፣ ባህላዊ ሙዚቀኞችና የቲያትር አርቲስቶች የተዘጋጀ የ12 ወራት የነጻ ስልጠናና ድጋፍ።',
    fullContent:
      'Kin Ethiopia invites applications from artists aged 18–28. The fellowship includes housing support in Addis Ababa, daily training, injury-prevention sessions, and a place in the 2027 city season. Applicants should prepare a two-minute work sample and a short letter describing what they want to learn. Deadline: 20 October 2026. Email fellowship@kinethiopia.org.',
    amharicFullContent:
      'ኪን ኢትዮጵያ ዕድሜያቸው ከ18–28 የሆኑ ወጣት አርቲስቶችን ይጋብዛል። ድጋፉ በአዲስ አበባ የመኖሪያ አበል፣ የዕለት ተዕለት ስልጠናና በመድረክ ላይ የመሳተፍ ዕድልን ያካትታል። እስከ ጥቅምት 10 ቀን 2019 ዓ.ም ድረስ በ fellowship@kinethiopia.org ይመዝገቡ።',
    imageUrl: '/images/events/kin-cultural-exchange.jpg',
    featured: true,
  },
  {
    id: 'a2',
    slug: 'entoto-weekend-workshops',
    title: 'Weekend workshops continue in Entoto',
    amharicTitle: 'የሳምንት መጨረሻ አውደ ጥናቶች በእንቶቶ ቀጥለዋል',
    date: '2026-08-28',
    category: 'Workshops',
    amharicCategory: 'አውደ ጥናቶች',
    summary: 'Free Saturday sessions in percussion, washint, and floor tumbling for young people.',
    amharicSummary: 'ለወጣቶች በነጻ የሚሰጥ የከበሮ፣ ዋሽንትና የአክሮባቲክስ ቅዳሜ ስልጠና።',
    fullContent:
      'On the first and third Saturday of each month, principal artists host open workshops at the Kin Pavilion. Sessions run 10:00–12:30. Bring water. Instruments are provided. Parents may wait in the courtyard.',
    amharicFullContent:
      'በየወሩ በሁለቱ ቅዳሜዎች ከጠዋቱ 4:00 እስከ 6:30 በእንቶቶ ኪን ፓቪሊዮን የነጻ ስልጠና ይሰጣል። የሙዚቃ መሣሪያዎች በቦታው ይዘጋጃሉ።',
    imageUrl: '/images/culture/kin-vocalists-performance.jpg',
  },
  {
    id: 'a3',
    slug: 'studio-closed-meskel',
    title: 'Studio calendar around Meskel',
    amharicTitle: 'የመስቀል በዓል የስቱዲዮ መርሃ ግብር',
    date: '2026-09-20',
    category: 'Notices',
    amharicCategory: 'ማስታወቂያዎች',
    summary: 'Rehearsal rooms close 26–28 September. Community workshops resume 3 October.',
    amharicSummary: 'የልምምድ ክፍሎች ከመስከረም 16–18 ይዘጋሉ። አውደ ጥናቶች ከመስከረም 23 ቀጥለው ይካሄዳሉ።',
    fullContent:
      'The training studio and box office will close from 26 to 28 September for Meskel. Emergency contact remains the company phone. We wish our neighbours a good feast.',
    amharicFullContent:
      'ለስቅለትና መስቀል በዓል የስቱዲዮ ልምምድ ክፍሎች ከመስከረም 16 እስከ 18 ዝግ ይሆናሉ። መልካም የመስቀል በዓል እንመኛለን።',
  },
  {
    id: 'a4',
    slug: 'instrument-makers-call',
    title: 'Call for krar and kebero makers',
    amharicTitle: 'የክራርና ከበሮ ሠሪዎች ጥሪ',
    date: '2026-07-09',
    category: 'Opportunities',
    amharicCategory: 'ዕድሎች',
    summary: 'We are commissioning a small run of rehearsal instruments from Ethiopian makers.',
    amharicSummary: 'ለስቱዲዮ ልምምድ የሚሆኑ የኢትዮጵያ ባህላዊ የሙዚቃ መሣሪያዎች ሠሪዎችን እንፈልጋለን።',
    fullContent:
      'Abesolom is gathering makers who can deliver concert-grade krar and kebero for studio use. Send photographs of recent instruments and your workshop location to crafts@kinethiopia.org.',
    amharicFullContent:
      'ጥራት ያላቸውን ክራሮችና ከበሮዎችን የሚሠሩ ባለሙያዎች የሥራዎቻቸውን ፎቶግራፍ በ crafts@kinethiopia.org እንዲልኩልን እንጋብዛለን።',
    imageUrl: '/images/hero/kin-ethiopia-golden-banner.jpg',
  },
  {
    id: 'a5',
    slug: 'press-night-echoes',
    title: 'Press night for Echoes of the Ridge',
    amharicTitle: 'የጋዜጠኞች ምሽት፡ የደጋው ንቅናቄ',
    date: '2026-09-04',
    category: 'Press',
    amharicCategory: 'ፕሬስ',
    summary: 'Accredited writers and photographers may request seats for 16 October.',
    amharicSummary: 'ጋዜጠኞችና ፎቶግራፈሮች በጥቅምት 6 ትይንት ላይ ለመገኘት ቦታ መያዝ ይችላሉ።',
    fullContent:
      'A press preview of Echoes of the Ridge will be held on 16 October at the National Theatre. Write to press@kinethiopia.org.',
    amharicFullContent:
      'የደጋው ንቅናቄ ትይንት የጋዜጠኞች ቅድመ-ዕይታ በጥቅምት 6 ቀን በብሔራዊ ቲያትር ይካሄዳል። በ press@kinethiopia.org ያግኙን።',
  },
];

export const mockGallery: GalleryItem[] = [
  {
    id: 'g1',
    imageUrl: '/images/hero/kin-grand-stage-ensemble.jpg',
    alt: 'Three-tier human pyramid in rehearsal',
    caption: 'Kin Main Stage Ensemble Performance',
    amharicCaption: 'የኪን ዋና መድረክ ትይንትና የአክሮባቲክስ ሰርከስ',
    category: 'Circus',
    amharicCategory: 'ሰርከስ',
    location: 'Addis Ababa',
    amharicLocation: 'አዲስ አበባ',
    uploadedAt: '2026-08-01',
  },
  {
    id: 'g2',
    imageUrl: '/images/culture/kin-vocalists-performance.jpg',
    alt: 'Krar player and vocalists in low studio light',
    caption: 'Traditional Vocal Ensemble and Instrumentalists',
    amharicCaption: 'የባህላዊ ድምፃውያንና የክራር ተጫዋቾች ቡድን',
    category: 'Music',
    amharicCategory: 'ሙዚቃ',
    location: 'Gondar residency',
    amharicLocation: 'ጎንደር',
    uploadedAt: '2026-07-12',
  },
  {
    id: 'g3',
    imageUrl: '/images/hero/kin-ethiopia-golden-banner.jpg',
    alt: 'Kin Ethiopia Golden Stage Banner',
    caption: 'Kin Ethiopia Grand Stage Title',
    amharicCaption: 'የኪን ኢትዮጵያ ወርቃማ የመድረክ ርዕስ',
    category: 'Events',
    amharicCategory: 'ሁነቶች',
    location: 'Entoto Pavilion',
    amharicLocation: 'እንቶቶ ፓቪሊዮን',
    uploadedAt: '2026-06-20',
  },
  {
    id: 'g4',
    imageUrl: '/images/events/kin-cultural-exchange.jpg',
    alt: 'Young dancers in a workshop circle',
    caption: 'International Cultural Exchange Gathering',
    amharicCaption: 'ዓለም አቀፍ የባህል ልውውጥና የወጣቶች ውዝዋዜ',
    category: 'Community',
    amharicCategory: 'ማኅበረሰብ',
    location: 'Addis Ababa',
    amharicLocation: 'አዲስ አበባ',
    uploadedAt: '2026-05-03',
  },
];
